plugins {
    id 'dev.gradleplugins.java-gradle-plugin'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    alias libs.plugins.licenser
    alias libs.plugins.gradleutils
}

final projectDisplayName = 'ForgeGradle'
final projectArtifactId = base.archivesName = project.name // cannot change this
group = 'net.minecraftforge.gradle'
version = gitversion.tagOffset

println "Version: $version"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

sourceSets {
    register('common')
    register('mcp')
    register('patcher')
    register('userdev')
}

configurations {
    configureEach {
        exclude group: 'org.ow2.asm'
    }

    def extend = { String to, String... from ->
        final SourceSet toSet = sourceSets.getByName(to)

        for (var s in from) {
            final SourceSet fromSet = sourceSets.getByName(s)

            named(toSet.implementationConfigurationName) { extendsFrom getByName(fromSet.implementationConfigurationName) }
            named(toSet.compileOnlyConfigurationName) { extendsFrom getByName(fromSet.compileOnlyConfigurationName) }
        }
    }

    extend('mcp', 'common')
    extend('patcher', 'common')
    extend('userdev', 'mcp')
    extend('main', 'mcp', 'patcher', 'userdev')
}

// See settings.gradle for why this is here
repositories {
    mavenCentral()
    maven gradleutils.forgeMaven
}

dependencies {
    commonCompileOnly gradleApi(libs.versions.gradle.get())
    commonCompileOnly libs.bundles.groovy

    commonImplementation libs.commons.io
    commonImplementation libs.lzma
    commonImplementation libs.javaxdelta
    commonImplementation libs.gson
    commonImplementation libs.guava
    commonImplementation libs.fastcsv
    commonImplementation libs.artifactural
    commonImplementation libs.maven.artifact
    commonImplementation libs.httpclient
    commonImplementation libs.srgutils
    commonImplementation variantOf(libs.diffpatch) { classifier 'all' }

    mcpImplementation sourceSets.common.output
    patcherImplementation sourceSets.mcp.output
    patcherImplementation sourceSets.common.output
    userdevImplementation sourceSets.mcp.output
    userdevImplementation sourceSets.common.output
}

tasks.named('jar', Jar) {
    from sourceSets.common.output
    from sourceSets.mcp.output
    from sourceSets.patcher.output
    from sourceSets.userdev.output
}

license {
    header = rootProject.file('LICENSE-header.txt')
    ext {
        name = 'ForgeGradle'
        year = 2018
        fullname = 'Forge Development LLC'
    }
    exclude '**/*.properties'
    exclude 'net/minecraftforge/gradle/common/diff/'
    exclude 'net/minecraftforge/gradle/common/util/JavaVersionParser.java'
}

gradlePlugin {
    website.set gitversion.url
    vcsUrl.set gitversion.url + '.git'

    compatibility {
        minimumGradleVersion = libs.versions.gradle.get()
    }

    java {
        withSourcesJar()
    }

    plugins {
        // UserDev
        register('userdev') {
            id = 'net.minecraftforge.gradle'
            implementationClass = 'net.minecraftforge.gradle.userdev.UserDevPlugin'
        }

        // MCP
        def mcp = { String name ->
            register(name) {
                it.id = "net.minecraftforge.gradle.${name.replace('-', '.')}"
                it.implementationClass = 'net.minecraftforge.gradle.mcp.MCPPlugin'
            }
        }
        mcp('mcp')
        mcp('forgedev-mcp')

        // Patcher
        def patcher = { String name ->
            register(name) {
                it.id = "net.minecraftforge.gradle.${name.replace('-', '.')}"
                it.implementationClass = 'net.minecraftforge.gradle.patcher.PatcherPlugin'
            }
        }
        patcher('patcher')
        patcher('forgedev')
        patcher('forgedev-patcher')
    }
}

publishing {
    publications.register('pluginMaven', MavenPublication) {
        artifactId = projectArtifactId

        pom { pom ->
            name = projectDisplayName

            gradleutils.pom.setGitHubDetails pom

            licenses {
                license gradleutils.pom.licenses.LGPLv2_1
            }
        }
    }

    repositories {
        maven gradleutils.publishingForgeMaven
    }
}
