import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import org.gradle.api.plugins.jvm.JvmTestSuite
import org.gradle.api.tasks.testing.logging.TestExceptionFormat

plugins {
    id 'java-gradle-plugin'
    id 'jvm-test-suite'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    id 'local.build.jdt-transformer'
    id 'io.freefair.javadoc-links'
    id 'net.minecraftforge.gradleutils'
    alias libs.plugins.licenser
    alias libs.plugins.gitversion
    alias libs.plugins.changelog
    alias libs.plugins.shadow
}

description = 'Gradle plugin for Forge'
group = 'net.minecraftforge.gradle'
version = gitversion.tagOffset

java {
    toolchain.languageVersion = JavaLanguageVersion.of(8)
    withSourcesJar()
    //withJavadocJar()
}

gradleutils.pluginDevDefaults(configurations, libs.versions.gradle)

configurations {
    dependencyScope('shade')

    named('implementation') {
        extendsFrom shade
    }

    resolvable('shadeClasspath') {
        extendsFrom shade
    }

    named('shadowRuntimeElements') {
        withDependencies {
            addAll(runtimeClasspath.allDependencies)
            removeAll(shade.allDependencies)
        }
    }

    configureEach {
        resolutionStrategy {
            force libs.asm.commons
            force libs.asm.tree
            force libs.asm
        }
    }
}

dependencies {
    compileOnly libs.gradle
    compileOnly libs.groovy

    // moved to the beginning to be the overrider
    //implementation libs.asm.debug
    implementation libs.guava

    implementation libs.opencsv // reading CSVs.. also used by SpecialSource
    implementation libs.diff4j // for difing and patching
    implementation libs.jastyle // formatting
    implementation libs.trove4j // because its awesome.

    implementation libs.lzma // replaces the LZMA binary
    implementation libs.xdelta // GDIFF implementation for BinPatches
    implementation libs.gson // Used instead of Argo for buuilding changelog.
    implementation libs.named.regexp // 1.7 Named regexp features
    implementation libs.forgeflower // Fernflower Forge edition

    shade libs.specialsource // deobf and reobf

    // because curse
    implementation libs.httpclient
    implementation libs.httpmime

    // mcp stuff
    shade libs.retroguard
    shade(libs.mcinjector) {
        exclude group: 'org.ow2.asm'
    }
    shade(libs.srg2source) {
        exclude group: 'cpw.mods', module: 'modlauncher'
        exclude group: 'org.ow2.asm'
        exclude group: 'org.eclipse.equinox', module: 'org.eclipse.equinox.common'

        jdt.transform(it)
    }
    constraints {
        shade('org.eclipse.jdt:org.eclipse.jdt.core') {
            jdt.transform(it)
        }
    }

    // Because Eclipse is dumb and decided to use dynamic versions with J8 incompatibility
    shade libs.eclipse.core.resources
    shade libs.eclipse.core.runtime
    shade libs.eclipse.text
    shade libs.eclipse.core.filesystem
    shade libs.eclipse.equinox.common
    shade libs.eclipse.core.contenttype
    shade libs.eclipse.core.jobs
    shade libs.eclipse.equinox.registry
    shade libs.eclipse.osgi
    shade libs.eclipse.core.commands

    //Stuff used in the GradleStart classes
    compileOnly libs.authlib
    compileOnly(libs.launchwrapper) {
        exclude group: 'org.ow2.asm'
    }

    compileOnly libs.kotlin.gradle.plugin
}

testing {
    suites.named('test', JvmTestSuite) {
        useJUnit(libs.versions.junit)

        dependencies {
            implementation libs.gradle.testkit
        }

        targets.configureEach {
            testTask.configure {
                ignoreFailures = true
                javaLauncher = javaToolchains.launcherFor { languageVersion = JavaLanguageVersion.of(8) }
                testLogging { exceptionFormat = TestExceptionFormat.FULL }
            }
        }
    }
}

tasks.named('compileJava', JavaCompile) {
    options.deprecation = true
    //options.compilerArgs += ["-Werror"]
    //options.compilerArgs += ["-Werror", "-Xlint:unchecked"]
}

tasks.named('validatePlugins', ValidatePlugins) {
    enabled = false
}

tasks.named('processResources', ProcessResources) { task ->
    task.inputs.property('version', project.version)

    task.filesMatching('forgegradle.version.txt') {
        expand 'version': task.inputs.properties.version
    }
}

tasks.named('jar', Jar) {
    manifest {
        attributes([
            'group'                 : group,
            'version'               : version,
            'javaCompliance'        : java.targetCompatibility,
            'Implementation-Version': version + "-" + gitversion.info.hash
        ])
    }

    archiveClassifier = 'slim'
}

shadow {
    // Marks the jar as being embedded, not shadowed.
    // shadowed = relocated, embedded = no relocation.
    bundlingAttribute = Bundling.EMBEDDED
}

tasks.named('shadowJar', ShadowJar) {
    archiveClassifier = null
    configurations = [project.configurations.shadeClasspath]
    exclude '.api_description', '.options', 'about.html', 'module-info.class', 'plugin.properties', 'plugin.xml', 'about_files/**'
}

license {
    ext {
        description = 'A Gradle plugin for the creation of Minecraft mods and MinecraftForge plugins.'
        year = '2013-2019'
        fullname = 'Minecraft Forge'
    }

    header = rootProject.file('LICENSE-header.txt')
    newLine = false
    include '**net/minecraftforge/gradle/**/*.java'
    excludes = [
        '**net/minecraftforge/gradle/util/ZipFileTree.java',
        '**net/minecraftforge/gradle/util/json/version/*',
        '**net/minecraftforge/gradle/util/patching/Base64.java',
        '**net/minecraftforge/gradle/util/patching/ContextualPatch.java'
    ]
    ignoreFailures false
}

changelog {
    from '2.3'
}

gradlePlugin {
    website = gitversion.url
    vcsUrl = gitversion.url + '.git'

    plugins {
        configureEach {
            description = 'Gradle plugin for all Minecraft mod development needs'
            tags = ['forge', 'minecraft', 'minecraftforge', 'sponge', 'mcp']
        }

        register('patcher') {
            id = 'net.minecraftforge.gradle.patcher'
            displayName = 'Minecraft Patcher Plugin'
            implementationClass = 'net.minecraftforge.gradle.patcher.PatcherPlugin'
        }
        register('tweakerClient') {
            id = 'net.minecraftforge.gradle.tweaker-client'
            displayName = 'Minecraft Client Tweaker Plugin'
            implementationClass = 'net.minecraftforge.gradle.user.tweakers.ClientTweaker'
        }
        register('tweakerServer') {
            id = 'net.minecraftforge.gradle.tweaker-server'
            displayName = 'Minecraft Server Tweaker Plugin'
            implementationClass = 'net.minecraftforge.gradle.user.tweakers.ServerTweaker'
        }
        register('forge') {
            id = 'net.minecraftforge.gradle.forge'
            displayName = 'MinecraftForge Mod Development Plugin'
            implementationClass = 'net.minecraftforge.gradle.user.patcherUser.forge.ForgePlugin'
        }
        register('launch4j') {
            id = 'net.minecraftforge.gradle.launch4j'
            displayName = 'Specialized Launch4J Gradle Plugin'
            implementationClass = 'edu.sc.seis.launch4j.Launch4jPlugin'
        }
        register('liteloader') {
            id = 'net.minecraftforge.gradle.liteloader'
            displayName = 'LiteLoader Mod Development Plugin'
            implementationClass = 'net.minecraftforge.gradle.user.liteloader.LiteloaderPlugin'
        }
    }
}

shadow {
    // Skips the automatic addition of the shadow variant into the Java component. We do that ourselves.
    // The reason is because shadow calls mapToOptional(), which we cannot revert. The dependencies are not optional.
    addShadowVariantIntoJavaComponent = false
}

afterEvaluate {
    // Skips publishing the slim jar as a component. This makes the POM inherit the shadowRuntimeElements dependencies.
    (components.java as AdhocComponentWithVariants).withVariantsFromConfiguration(configurations.runtimeElements) {
        skip()
    }

    // Adds the shadowRuntimeElements variant to the Java component.
    (components.java as AdhocComponentWithVariants).addVariantsFromConfiguration(configurations.shadowRuntimeElements) {}
}

publishing {
    repositories {
        maven gradleutils.publishingForgeMaven
    }

    publications.register('pluginMaven', MavenPublication) {
        changelog.publish(it)
        gradleutils.promote(it)

        pom { pom ->
            name = gradleutils.displayName
            description = project.description

            gradleutils.pom.addRemoteDetails(pom)

            licenses {
                license gradleutils.pom.licenses.LGPLv2_1
            }

            developers {
                developer {
                    id = 'AbrarSyed'
                    name = 'Abrar Syed'
                }
                developer gradleutils.pom.developers.LexManos
            }
        }
    }
}
