[versions]
forgeGradle = "6.0"

commonsIo = "2.16.1" # https://mvnrepository.com/artifact/commons-io/commons-io
commonsLang = "3.17.0" # https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
gson = "2.11.0" # https://mvnrepository.com/artifact/com.google.code.gson/gson
guava = "33.3.0-jre" # https://mvnrepository.com/artifact/com.google.guava/guava
fastcsv = "2.2.2" # https://mvnrepository.com/artifact/de.siegmar/fastcsv
artifactural = "3.0.19" # https://files.minecraftforge.net/net/minecraftforge/artifactural/index.html
unsafe = "0.9.2" # https://files.minecraftforge.net/net/minecraftforge/unsafe/index.html
mavenArtifact = "3.9.9" # https://mvnrepository.com/artifact/org.apache.maven/maven-artifact
httpClient = "4.5.14" # https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient
srgUtils = "0.5.11" # https://files.minecraftforge.net/net/minecraftforge/srgutils/index.html
diffPatch = "2.0.12" # https://files.minecraftforge.net/net/minecraftforge/DiffPatch/index.html
jarJarMetadata = "0.3.19"
jarJarSelector = "0.3.19"

licenser = "1.0.1" # https://plugins.gradle.org/plugin/net.minecraftforge.licenser
gradleUtils = "[2.3,2.4)" # https://plugins.gradle.org/plugin/net.minecraftforge.gradleutils
versions = "0.51.0" # https://plugins.gradle.org/plugin/com.github.ben-manes.versions

[libraries]

commons-io = { module = "commons-io:commons-io", version.ref = "commonsIo" }
commons-lang = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
fastcsv = { module = "de.siegmar:fastcsv", version.ref = "fastcsv" }
artifactural = { module = "net.minecraftforge:artifactural", version.ref = "artifactural" }
unsafe = { module = "net.minecraftforge:unsafe", version.ref = "unsafe" }
maven-artifact = { module = "org.apache.maven:maven-artifact", version.ref = "mavenArtifact" }
http-client = { module = "org.apache.httpcomponents:httpclient", version.ref = "httpClient" }
srgUtils = { module = "net.minecraftforge:srgutils", version.ref = "srgUtils" }
diffPatch = { module = "net.minecraftforge:DiffPatch", version.ref = "diffPatch" }
jarJar-metadata = { module = "net.minecraftforge:JarJarMetadata", version.ref = "jarJarMetadata" }
jarJar-selector = { module = "net.minecraftforge:JarJarSelector", version.ref = "jarJarSelector" }

[plugins]

licenser = { id = "net.minecraftforge.licenser", version.ref = "licenser" }
gradleUtils = { id = "net.minecraftforge.gradleutils", version.ref = "gradleUtils" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }