plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention'
    id 'net.minecraftforge.gradleutils'
}

rootProject.name = 'buildSrc'

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven gradleutils.forgeMaven
        maven { url = 'https://maven.moddinglegacy.com/maven' } // Gradle API
        //mavenLocal()
    }

    //@formatter:off
    versionCatalogs.register('libs') {
        plugin 'licenser', 'net.minecraftforge.licenser' version '1.2.0'

        // Gradle API
        version 'gradle', '9.0.0'
        library 'gradle', 'name.remal.gradle-api', 'gradle-api'  versionRef 'gradle'

        library 'nulls', 'org.jetbrains', 'annotations' version '26.0.2'

        // GradleUtils Shared Base
        library 'gradleutils-shared', 'net.minecraftforge', 'gradleutils-shared' version '3.3.5'

        version 'asm', '6.2.1'
        library 'asm',      'org.ow2.asm', 'asm'      versionRef 'asm'
        library 'asm-tree', 'org.ow2.asm', 'asm-tree' versionRef 'asm'
        bundle  'asm', ['asm', 'asm-tree']
    }
    //@formatter:on
}